In [3]:
import numpy as np

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

In [4]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ -6.17452388  -3.25152322   0.44884069 ... -15.70005137   6.32048201
    6.42795674]
 [ -5.43848549  13.93639021  11.8794656  ...   0.70205264  -0.90195727
  -15.26885721]
 [ -3.98501998  15.83183273  -7.98029223 ...  -4.07175578 -13.60358976
   -7.58099301]
 ...
 [  1.78412043   5.52058731 -16.87449553 ... -17.84607483  -3.48779231
    0.55380664]
 [  0.16166157  12.03764846   3.47238639 ...   7.97865033 -13.64697325
   -7.82744543]
 [ 16.33956404 -13.04121868 -12.52637271 ...   3.59316323   3.51124815
    1.53638829]]


Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

In [5]:
m = np.mean(X, axis=0) # sum(X) / len(X)
std = np.std(X, axis=0) #((sum((x_i - m) ** 2) / n) ** 0.5
X_norm = (X - m) / std
print(X_norm)

[[-0.70610255 -0.38824689 -0.04030936 ... -1.69375337  0.57129547
   0.55446916]
 [-0.63207442  1.31190265  1.06077563 ... -0.02931913 -0.16636068
  -1.6780953 ]
 [-0.48589     1.49939113 -0.85226774 ... -0.51375029 -1.46362839
  -0.88702743]
 ...
 [ 0.09434973  0.47945004 -1.70902525 ... -1.91152512 -0.43046219
  -0.04997068]
 [-0.06883144  1.12408783  0.25094163 ...  0.70908725 -1.46805932
  -0.91238696]
 [ 1.55828474 -1.35659865 -1.29018089 ...  0.26406173  0.28437736
   0.05113526]]


Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

In [6]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [7]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

In [8]:
A, B = np.eye(3), np.eye(3)
print(np.vstack((A, B)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Предобработка данных в Pandas

In [9]:
import pandas

загрузки данных в Pandas

In [10]:
#колонка PassengerId задает нумерацию строк данного датафрейма.
data = pandas.read_csv('titanic.csv', index_col='PassengerId')

In [11]:
print(data[30:40])

             Survived  Pclass                                            Name  \
PassengerId                                                                     
31                  0       1                        Uruchurtu, Don. Manuel E   
32                  1       1  Spencer, Mrs. William Augustus (Marie Eugenie)   
33                  1       3                        Glynn, Miss. Mary Agatha   
34                  0       2                           Wheadon, Mr. Edward H   
35                  0       1                         Meyer, Mr. Edgar Joseph   
36                  0       1                  Holverson, Mr. Alexander Oskar   
37                  1       3                                Mamee, Mr. Hanna   
38                  0       3                        Cann, Mr. Ernest Charles   
39                  0       3              Vander Planke, Miss. Augusta Maria   
40                  1       3                     Nicola-Yarred, Miss. Jamila   

                Sex   Age  

In [12]:
print(data.head())

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S

In [13]:
#amount of passengers in each class
print(data['Pclass'].value_counts())

3    491
1    216
2    184
Name: Pclass, dtype: int64


# Task

Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел.

In [14]:
print(data['Sex'].value_counts())

male      577
female    314
Name: Sex, dtype: int64


Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [15]:
survived = round((data['Survived'].value_counts()[1] / len(data)) * 100, 2)

In [16]:
print(survived)

38.38


Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.


In [17]:
first_class = round(data['Pclass'].value_counts()[1] / len(data) * 100, 2)

In [18]:
print(first_class)

24.24


Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.

In [19]:
age_mean = round((np.mean(data['Age'].dropna())), 2)
age_median = round(data['Age'].dropna().median(), 2)

In [20]:
print(age_mean)
print(age_median)

29.7
28.0


Коррелируют ли число братьев/сестер с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch.

In [21]:
sibsp = np.array([x for x in (data['SibSp'] - np.mean(data['SibSp']))])
parch = np.array([x for x in (data['Parch'] - np.mean(data['Parch']))])
m = np.array([(x * y) for x, y in zip(sibsp, parch)])
sibsp = np.array([x ** 2 for x in sibsp])
parch = np.array([x ** 2 for x in parch])

In [22]:
r = np.sum(m) / (np.sum(sibsp) * np.sum(parch)) ** 0.5

In [23]:
print(round(r, 2))

0.41


In [24]:
data.corr(method='pearson')

Survived    Pclass       Age     SibSp     Parch      Fare
Survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
Pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
Age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
SibSp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
Parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
Fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Это задание — типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию. Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения их на женские и мужские.

In [25]:
name = [line for line in data['Name'] if 'Mrs.' in line or 'Miss.' in line]
for line in name:
    if '(' in line:
        name[name.index(line)] = line[line.find("(")+1:line.find(")")]
    elif 'Mrs.' in line:
        name[name.index(line)] = line.split()[line.split().index('Mrs.') + 1]
    elif 'Miss.' in line:
        name[name.index(line)] = line.split()[line.split().index('Miss.') + 1]
    else:
        continue

In [29]:
Name = {}
for i in name:
    Name[i] = Name.get(i, 0) + 1
print(sorted(Name.items(), key=lambda x: x[1], reverse=True)[0])

('Anna', 10)
